config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  # get "/books", to: "books#index", as: "books" #books_path = /books
  # get "/books/new" , to: "books#new", as: "new_book" #new_book_path = /books/new
  # get "/books/:id/edit", to: "books#edit" , as: "edit_book" #edit_book_path(@book)
  # get "/books/:id", to: "books#show", as:"book" # book_path(book) =/books/:id
  # delete "/books/:id", to: "books#destroy" # delete the shortcut book_path(book) =/books/:id already there
  # post "/books", to: "books#create"
  # patch "/books/:id", to:"books#update"
  #books


  # author nested becuse the  the book has many to one relation
  resources :authors do
    resources :books
  end
  # get "/authors", to: "authors#index", as: "authors"
  # get "/authors/new", to: "authors#new", as:"new_author"
  # get "/authors/:id/edit", to: "authors#edit", as: "edit_author"
  # get "/authors/:id", to:"authors#show", as: "author"
  # delete "authors/:id", to:"authors#destroy"
  # post "/authors", to: "authors#create"
  # patch "authors/:id", to: "authors#update"

  #patient
  resources :patients
  # get "/patients", to: "patients#index", as:"patients"
  # get "/patients/new", to:"patients#new", as:"new_patient"
  # get "/patients/:id/edit", to:"patients#edit", as:"edit_patient"
  # get "/patients/:id", to:"patients#show", as: "patient"
  # delete "/patients/:id", to:"patients#destroy"
  # post "/patients", to:"patients#create"
  # patch "/patients/:id", to:"patients#update"


  root "welcome#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

    def index
        @authors = Author.all
    end
    def show
        @author = Author.find(params[:id])
    end

    def destroy
        @author = Author.find(params[:id])
        @author.destroy

        redirect_to authors_path
    end
    def new
        @author = Author.new
    end

    def create
        @author = Author.create(authors_params)

        redirect_to authors_path(@author)
    end

    def edit
        @author = Author.find(params[:id])
    end

    def update
        @author = Author.find(params[:id])
        @author.update(authors_params)

        redirect_to authors_path(@author)
    end
    def authors_params
        params.require(:author).permit(:first_name ,:last_name, :location, :nickname, :hometown ,:age)
    end
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @author = Author.find(params[:author_id])
        @books = @author.books
    end
    def show
        @author = Author.find(params[:author_id])
        @book = @author.books.find(params[:id])
    end
    def destroy
        @author = Author.find(params[:author_id])
        @book = @author.books.find(params[:id])
        @book.destroy
        
        redirect_to author_books_path(@author)
    end
    def new
        @author = Author.find(params[:author_id])
        @book = @author.books.new
    end

    def create
        @author = Author.find(params[:author_id])
        @book = @author.books.create(book_params)

        # redirect_to books_path
        redirect_to author_books_path(@author, @book)
    end

    def edit
        @author = Author.find(params[:author_id])
        @book = @author.books.find(params[:id])
    end

    def update
        @author = Author.find(params[:author_id])
        @book = @author.books.find(params[:id])
        @book.update(book_params)
        # redirect_to books_path
        redirect_to author_books_path(@author, @book)
    end

    def book_params
        params.require(:book).permit(:title,:print_date,:original_language)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    def index
        @patients = Patient.all
    end
    def show
        @patient = Patient.find(params[:id])
    end
    def destroy
        @patient = Patient.find(params[:id])
        @patient.destroy

        redirect_to patients_path
    end
    def new
        @patient = Patient.new
    end
    def create
        @patient = Patient.create(patients_params)

        redirect_to patients_path(@patient)
    end
    def edit
        @patient = Patient.find(params[:id])
    end
    def update
        @patient = Patient.find(params[:id])
        @patient.update(patients_params)

        redirect_to patients_path(@patient)
    end
    def patients_params
        params.require(:patient).permit(:first_name ,:last_name, :diagnosis,:born_on)
    end
end


#Patient.create({first_name:"Wijdan", last_name:"Kuddah", diagnosis:"Flu", born_on:Date.parse('1995-01-05')})

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authors/edit.html.erb
<h1>Update author information</h1>

<%= form_for @author, url:{action: "update"} do |a| %>
    <%= a.label :first_name %>
    <%= a.text_field :first_name %>
    <%= a.label :last_name %>
    <%= a.text_field :last_name %>
    <%= a.label :nickname %>
    <%= a.text_field :nickname %>
    <%= a.label :age %>
    <%= a.number_field :age %>
    <%= a.label :location %>
    <%= a.text_field :location %>
    <%= a.label :hometown %>
    <%= a.text_field :hometown %>
    <%= a.submit "Save" %>
<%end%>

app/views/authors/index.html.erb
<h1>Authors</h1>

<h3><%= link_to "Add new author", new_author_path %></h3>

<% @authors.each do |author| %>

<p>
<%= link_to author.first_name, author_path(author) %>
<%= author.last_name %>
<%= author.nickname %>
<%= author.age %>
<%= author.location %>

</p>

<%end%>

app/views/authors/new.html.erb
<h1>Add new author</h1>

<%= form_for @author, url:{action: "create"} do |a| %>
    <%= a.label :first_name %>
    <%= a.text_field :first_name %>
    <%= a.label :last_name %>
    <%= a.text_field :last_name %>
    <%= a.label :nickname %>
    <%= a.text_field :nickname %>
    <%= a.label :age %>
    <%= a.number_field :age %>
    <%= a.label :location %>
    <%= a.text_field :location %>
    <%= a.label :hometown %>
    <%= a.text_field :hometown %>
    <%= a.submit "Save" %>
<%end%>

app/views/authors/show.html.erb
<h1> Show</h1>
<p><%= link_to "Back" , authors_path %> 
</p>
<p>
<%= @author.first_name %>
<%= @author.last_name %>
<%= @author.nickname %>
<%= @author.age %>
<%= @author.location %>
<%= @author.hometown %>

<%= link_to "Show Books", author_books_path( @author) %>
<%= link_to "Edit", edit_author_path(@author) %>
<%= link_to "Delete this author", author_path(@author), method: :delete %>
</p>

app/views/books/edit.html.erb
<h1> Update your book </h1>

<%= form_for @book, url: {action: "update"} do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :print_date %>
    <%= f.date_field :print_date %>
    <%= f.label :original_language %>
    <%= f.text_field :original_language %>
    <%= f.submit "Save" %>
<% end%>

app/views/books/index.html.erb
<h1><%= @author.first_name %>'s Books</h1>

<h3><%= link_to "Create a book", new_author_book_path(@author) %></h3>

<% @books.each do |book| %>

<h3>
  <%= link_to book.title, author_book_path(@author, book) %>
</h3>

<% end %>

app/views/books/new.html.erb
<h1> Add your book </h1>
<%= form_for @book, url: {action: "create"} do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :print_date %>
    <%= f.date_field :print_date %>
    <%= f.label :original_language %>
    <%= f.text_field :original_language %>
    <%= f.submit "Save" %>
<% end%>

app/views/books/show.html.erb
<p> <%= link_to "Back" , author_books_path(@author) %> 

</p>
<h1>
<%= @book.title %>
</h1>

<p>
<%= @book.print_date %>
</p>

<p>
<%= @book.original_language %>
</p>


<p>

<%= link_to "Edit", edit_author_book_path(@author, @book) %>
<%= link_to "Destroy this book!", author_book_path(@author, @book), method: :delete %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/edit.html.erb
<h1>Update patient information</h1>

<%= form_for @patient, url:{action: "update"} do |p| %>
    <%= p.text_field :first_name %>
    <%= p.text_field :last_name %>
    <%= p.text_field :diagnosis %>
    <%= p.date_field :born_on %>
    <%= p.submit "Save" %>
<%end%>

app/views/patients/index.html.erb
<h1>Patients</h1>
<h3><%= link_to "New patient", new_patient_path %></h3>

<% @patients.each do |patient| %>

<p>
<%=link_to patient.first_name, patient_path(patient) %>
<%= patient.last_name %>
<%= patient.diagnosis %>
<%= patient.born_on %>
</p>

<%end%>

app/views/patients/new.html.erb
<h1>Add new patient</h1>

<%= form_for @patient, url:{action: "create"} do |p| %>
    <%= p.text_field :first_name %>
    <%= p.text_field :last_name %>
    <%= p.text_field :diagnosis %>
    <%= p.date_field :born_on %>
    <%= p.submit "Save" %>
<%end%>

app/views/patients/show.html.erb
<h1>Patient Information</h1>
<p><%= link_to "Back" , patients_path %> 
</p>

<p>

<%= @patient.first_name %>
<%= @patient.last_name %>
<%= @patient.diagnosis %>
<%= @patient.born_on %>

<%= link_to "Edit", edit_patient_path(@patient) %>
<%= link_to "Delete", patient_path(@patient), method: :delete %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<p>
<%= link_to "Authors" ,authors_path %>
</p>

<p>
<%= link_to "Patients" ,patients_path %>
</p>